# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: render-meetups

jobs:
  render-meetups:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Intall system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libavfilter-dev
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            github::rstudio/chromote
            github::jhelvy/xaringanBuilder
            any::here
            any::callr
            any::pdftools
            any::qpdf
            any::chromote
            any::xaringanBuilder
            any::rmarkdown
            any::xaringan
            any::magick

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_options = list(html_preview = FALSE))'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add meetups/* README.md
          git commit -m 'Render Meetups' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
